export const unknownServerError = "an unknown server error occurred";
export const invalidMessageError = "invalid message";
export const serviceError = "service error";
export const unknownDatabaseError = "an unknown database error occurred";
export const databaseError = "a database error occurred";
export const databaseConnectionError = "unable to connect to database server";
export const userNotFoundError = "user not found";
export const resourceNotFoundError = "resource not found";
export const incorrectCredentials = "email or password is incorrect";
export const invalidToken = "invalid token";
export const jwtError = "a JWT error occurred";
export const noPermissionError = "you do not have permission";
export const unauthorizedError = "unauthorized";
export const moduleError = "a module error occurred";
export const middlewareErrorLabel = "middleware error";
export const invalidUploadServer = "please use a valid upload server";
export const validationError = "a validation error occurred";
export const DATABASE_CONNECTION = "unable to connect to database server";
export const existError = (param: string) => `${param} already exist`;
export const notExistError = (param: string) => `${param} does not exist`;
